name: 构建与发布 ARM64

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release-arm64:
    name: 构建与发布 ARM64
    runs-on: ubuntu-22.04-arm
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Rust 环境
        uses: dtolnay/rust-toolchain@stable
      
      - name: 构建发布版本
        run: cargo build --release
      
      - name: 准备二进制文件
        run: |
          cp target/release/docxy docxy-linux-arm64
          chmod +x docxy-linux-arm64
      
      - name: 获取版本号
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: 上传到已存在的 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: |
            ./docxy-linux-arm64
